Workaround mergo merging
compose-spec/compose-go pull request #106
Opened 2021-02-17 16:30 UTC by ulyssessouza

This copies concrete values in the map to pointer values
then mergo can merge them.
After it copies that back to a concrete value type.

This should fix https://github.com/docker/compose-cli/issues/1261 and https://github.com/docker/cli/issues/2916

The process should probably be applied to other maps, like `networks`, `secrets`, `configs` and `extensions`

2021-02-17 20:45 UTC, ndeloof commented
If we adopt the "pointer" approach, then we need to do the same on all `map[]foo` types

2021-02-17 20:51 UTC, ulyssessouza commented
@ndeloof You are right!
This is just a "Draft" PR to check if there is something missing before I do the rest of the types

2021-02-17 20:57 UTC, ndeloof commented
Reading https://github.com/imdario/mergo/issues/90#issuecomment-435606388 it seems this would not be the sivler bullet you expected: non-empty source would be fully replaced by override, not merged.

2021-02-18 10:08 UTC, ndeloof commented
I ran my own debug session investigating https://github.com/docker/compose-cli/issues/1261 ...
surprisingly, mapstruct is able to set a `map` field (see https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L846) while mergo fails doing the same https://github.com/imdario/mergo/blob/cd55aeac72a19c6d5826061d5125d72b252a12eb/merge.go#L104
but that's all voodoo to me (ㆆ _ ㆆ)

I noticed (trying to get a minimal test set) that issue happens as compose override file defines `driver_opts` while the source has this map initial value set to nil
i.e adding an empty map in the yaml doc fix this issue:
```
volumes:
  data:
    driver_opts: {}
```
so a _possible_ fix, without digging into mergo internal reflect voodoo is to enforce all maps to be set.
mapstructure's `ZeroFields` could help us here, but unfortunately this only applies to keys in source, and other fields are skipped (https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L1350-L1353)
Need more investigations :P

2021-02-18 11:18 UTC, ndeloof requested changes
tested with 
```
volumes:
  data:
```
+ override:
```
volumes:
  data:
    driver: azure_file
    driver_opts:
      share_name: test-share
      storage_account_name: my-storage-account
```
as reported in initial issue

=> panic persists

by my own investigation, root cause is `DriverOpts` is a nil map and mergo fails to set a value.
Can't find a satisfying fix so far.

2021-02-23 13:16 UTC, ulyssessouza commented
@ndeloof You are right!
This is just a "Draft" PR to check if there is something missing before I do the rest of the types

2021-03-03 14:53 UTC, ulyssessouza commented
@ndeloof  Just waiting on merge of https://github.com/imdario/mergo/pull/177 to bump `mergo` to fix the `nil` issue

2021-03-04 09:02 UTC, ndeloof commented
@ulyssessouza https://github.com/imdario/mergo/pull/177 has been merged

2021-03-04 11:59 UTC, ulyssessouza commented
@ndeloof Yep! And I've just bumped mergo in this PR too

2021-03-04 13:04 UTC, ndeloof commented
ack, but with the fix you should not need to use `*types.VolumeConfig` anymore

2021-03-05 06:51 UTC, ndeloof approved these changes

2021-03-05 06:51 UTC, merged