Resolve environments case-insensitively on Windows
compose-spec/compose-go pull request #257
Opened 2022-05-03 03:53 UTC by ikedam

Please have a look on https://github.com/docker/compose/issues/9431 for details.

compose-go extracts environment variables to `Environment map[string]string` and reference that later with simply `Environment[varname]`.
It works case-sensitively but environment variables should be treated case-insensitively on Windows.

This change handles environment variables case-insensitively on Windows.

This change also adds exposed `utils.EnvResolver` function. I plan to use that for additional changes in https://github.com/docker/compose/ ,handling option args like `--build-arg` with `build` sub command and `-e` with `run` sub command.
(like this: https://github.com/ikedam/compose/pull/1/files)

2022-05-03 06:43 UTC, ndeloof commented
Thanks for looking into this!
For legal reasons, all commits need to be signed-off. Please amend your commit and force push your branch:
`git commit --amend --signoff && git push --force ...`

2022-05-03 06:52 UTC, ndeloof requested changes

2022-05-03 06:52 UTC, ndeloof commented on types/config.go
> +	v, ok := utils.EnvResolver(cd.Environment)(key)
as `EnvResolver` is not used in any other place, I'd prefer we keep things simple with `EnvResolverWithCase` logic being directly included here

2022-05-03 06:52 UTC, ndeloof commented on utils/envresolver.go
> +		if loweredEnvironment == nil {
No need to allocate a full lowercase map on each lookup, could just do
```go
key := strings.ToLower(s)
for k, v := range environment {
   if key == strings.ToLower(k) {
      return v
   }
}
```

2022-05-03 06:52 UTC, ndeloof commented on utils/envresolver_test.go
> +func Test_EnvResolverWithCase(t *testing.T) {
👍

2022-05-04 01:49 UTC, ikedam commented
> Thanks for looking into this! For legal reasons, all commits need to be signed-off. Please amend your commit and force push your branch: `git commit --amend --signoff && git push --force ...`

I've added signed-off line as described in https://github.com/compose-spec/compose-go/blob/master/CONTRIBUTING.md :
```
PS C:\workspace\compose-go> git log -n 1
commit 90f9d92dab00e1272c050960baeaaa8d8b15aaad (HEAD -> feature/9431_CaseInsensitiveEnv, ikedam/feature/9431_CaseInsensitiveEnv)
Author: ikedam <devld@ikedam.jp>
Date:   Tue May 3 11:58:23 2022 +0900

    Resolve environments case-insensitively on Windows

    Signed-off-by: IKEDA Yasuyuki <devld@ikedam.jp>
PS C:\workspace\compose-go>
```
But something might be wrong as this is the first time I wrote signed-off line.

Should I use the real name also in author line? Or should I add GPG signature? (git commit -S)

2022-05-04 02:13 UTC, ikedam commented
Oh, I got it. I have to pass DCO action. I'll try that.

2022-05-04 02:19 UTC, ikedam commented
Thanks for the review. I fixed problems you pointed.

2022-05-04 05:14 UTC, ndeloof approved these changes

2022-05-05 06:53 UTC, glours approved these changes
LGTM

2022-05-05 06:54 UTC, merged