fix regression considering volumes-from: container a dependency
compose-spec/compose-go pull request #384
Opened 2023-04-04 16:10 UTC by ndeloof

fix https://github.com/docker/compose/issues/10417

2023-04-06 13:39 UTC, glours requested changes
Sounds good, we should just add a test case for `volumes_from` with a service name

2023-04-06 13:59 UTC, ndeloof commented on loader/normalize_test.go
> +					"container:xxx",
there's no `service: xx` notation here, "zot" is already a service name

2023-04-07 08:08 UTC, glours approved these changes

2023-04-07 13:07 UTC, milas approved these changes
🙈

2023-04-07 14:09 UTC, merged