introduce ability to use custom env_file format
compose-spec/compose-go pull request #690
Opened 2024-10-01 15:39 UTC by ndeloof

This allows to register additional env_file format parser, so one can plug https://github.com/docker/cli/blob/master/opts/envfile.go as an alternate parser, to support reading "raw" env_file just like `docker run --env-file` does.

2024-10-02 14:52 UTC, jhrotko requested changes
LGTM! I would also add/change a test in `loader` to also cover this case

2024-10-02 14:52 UTC, jhrotko commented on types/project.go
> +		return nil, nil
```suggestion
		return nil, err
```

2024-10-02 14:54 UTC, ndeloof commented on types/project.go
> +		return nil, nil
indeed 😓

2024-10-02 15:35 UTC, ndeloof commented
@jhrotko a test in `loader` would make sense if we had an actual alternate format implementation hosted in this repo, but here we just define an extension point. raw loader test is [here](https://github.com/docker/compose/pull/12179/files#diff-f16f866ca631acf1a7182a4354c0e9bd3c0c2ebcb56c5a8754a703a5585037f6)

2024-10-03 10:00 UTC, jhrotko approved these changes
LGTM!

2024-10-04 08:46 UTC, glours approved these changes
LGTM

2024-10-07 07:16 UTC, merged